package com.pokemon.server.constant;

import javax.persistence.Table;

import com.pokemon.server.entity.*;

public final class Constants {
	private Constants() {
	}

	public static final String BLANK = "";
	public static final String NULL = "null";
	public static final String TRUE = "true";
	public static final String FALSE = "false";
	public static final String PATH_FOLDER_DATA = System.getProperty("user.dir") + "\\data\\";
	public static final String PATH_FOLDER_SQL = System.getProperty("user.dir") + "\\data\\sql\\";

	public static final String MSG_NOT_FOUND = "{0} with 【id = {1}】 not found !";
	public static final String MSG_TABLE_EMPTY = "Table 【{0}】 is empty !";
	public static final String MSG_CONFLICT = "{0} with 【id = {1}】 already exists !";

	public static final String MSG_FOUND_RECORD = "Found {0}:";
	public static final String MSG_FOUND_LIST = "Found 【{0}】 records !";
	public static final String MSG_CREATED = "Created {0}:";
	public static final String MSG_UPDATED = "Updated {0}:";
	public static final String MSG_DELETED = "{0} with 【id = {1}】  was deleted !";

	public static final String TABLE_ABILITY_NAME = Ability.class.getAnnotation(Table.class).name();
	public static final String TABLE_ABILITY_CHANGELOG_NAME = AbilityChangelog.class.getAnnotation(Table.class).name();
	public static final String TABLE_ABILITY_FLAVOR_TEXT_NAME = AbilityFlavorText.class.getAnnotation(Table.class).name();
	public static final String TABLE_BERRY_NAME = Berry.class.getAnnotation(Table.class).name();
	public static final String TABLE_BERRY_FIRMNESS_NAME = BerryFirmness.class.getAnnotation(Table.class).name();
	public static final String TABLE_BERRY_FLAVOR_NAME = BerryFlavor.class.getAnnotation(Table.class).name();
	public static final String TABLE_CHARACTERISTIC_NAME = Characteristic.class.getAnnotation(Table.class).name();
	public static final String TABLE_CONQUEST_EPISODE_NAME = ConquestEpisode.class.getAnnotation(Table.class).name();
	public static final String TABLE_CONQUEST_EPISODE_WARRIOR_NAME = ConquestEpisodeWarrior.class.getAnnotation(Table.class).name();
	public static final String TABLE_CONQUEST_KINGDOM_NAME = ConquestKingdom.class.getAnnotation(Table.class).name();
	public static final String TABLE_CONQUEST_MAX_LINK_NAME = ConquestMaxLink.class.getAnnotation(Table.class).name();
	public static final String TABLE_CONQUEST_MOVE_DATA_NAME = ConquestMoveData.class.getAnnotation(Table.class).name();
	public static final String TABLE_CONQUEST_MOVE_DISPLACEMENT_NAME = ConquestMoveDisplacement.class.getAnnotation(Table.class).name();
	public static final String TABLE_CONQUEST_MOVE_EFFECT_NAME = ConquestMoveEffect.class.getAnnotation(Table.class).name();
	public static final String TABLE_CONQUEST_MOVE_RANGE_NAME = ConquestMoveRange.class.getAnnotation(Table.class).name();
	public static final String TABLE_CONQUEST_POKEMON_ABILITY_NAME = ConquestPokemonAbility.class.getAnnotation(Table.class).name();
	public static final String TABLE_CONQUEST_POKEMON_EVOLUTION_NAME = ConquestPokemonEvolution.class.getAnnotation(Table.class).name();
	public static final String TABLE_CONQUEST_POKEMON_MOVE_NAME = ConquestPokemonMove.class.getAnnotation(Table.class).name();
	public static final String TABLE_CONQUEST_POKEMON_STAT_NAME = ConquestPokemonStat.class.getAnnotation(Table.class).name();
	public static final String TABLE_CONQUEST_STAT_NAME = ConquestStat.class.getAnnotation(Table.class).name();
	public static final String TABLE_CONQUEST_TRANSFORMATION_POKEMON_NAME = ConquestTransformationPokemon.class.getAnnotation(Table.class).name();
	public static final String TABLE_CONQUEST_TRANSFORMATION_WARRIOR_NAME = ConquestTransformationWarrior.class.getAnnotation(Table.class).name();
	public static final String TABLE_CONQUEST_WARRIOR_NAME = ConquestWarrior.class.getAnnotation(Table.class).name();
	public static final String TABLE_CONQUEST_WARRIOR_ARCHETYPE_NAME = ConquestWarriorArchetype.class.getAnnotation(Table.class).name();
	public static final String TABLE_CONQUEST_WARRIOR_RANK_NAME = ConquestWarriorRank.class.getAnnotation(Table.class).name();
	public static final String TABLE_CONQUEST_WARRIOR_RANK_STAT_MAP_NAME = ConquestWarriorRankStatMap.class.getAnnotation(Table.class).name();
	public static final String TABLE_CONQUEST_WARRIOR_SKILL_NAME = ConquestWarriorSkill.class.getAnnotation(Table.class).name();
	public static final String TABLE_CONQUEST_WARRIOR_SPECIALTY_NAME = ConquestWarriorSpecialty.class.getAnnotation(Table.class).name();
	public static final String TABLE_CONQUEST_WARRIOR_STAT_NAME = ConquestWarriorStat.class.getAnnotation(Table.class).name();
	public static final String TABLE_CONQUEST_WARRIOR_TRANSFORMATION_NAME = ConquestWarriorTransformation.class.getAnnotation(Table.class).name();
	public static final String TABLE_CONTEST_COMBO_NAME = ContestCombo.class.getAnnotation(Table.class).name();
	public static final String TABLE_CONTEST_EFFECT_NAME = ContestEffect.class.getAnnotation(Table.class).name();
	public static final String TABLE_CONTEST_TYPE_NAME = ContestType.class.getAnnotation(Table.class).name();
	public static final String TABLE_EGG_GROUP_NAME = EggGroup.class.getAnnotation(Table.class).name();
	public static final String TABLE_ENCOUNTER_NAME = Encounter.class.getAnnotation(Table.class).name();
	public static final String TABLE_ENCOUNTER_CONDITION_NAME = EncounterCondition.class.getAnnotation(Table.class).name();
	public static final String TABLE_ENCOUNTER_CONDITION_VALUE_NAME = EncounterConditionValue.class.getAnnotation(Table.class).name();
	public static final String TABLE_ENCOUNTER_CONDITION_VALUE_MAP_NAME = EncounterConditionValueMap.class.getAnnotation(Table.class).name();
	public static final String TABLE_ENCOUNTER_METHOD_NAME = EncounterMethod.class.getAnnotation(Table.class).name();
	public static final String TABLE_ENCOUNTER_SLOT_NAME = EncounterSlot.class.getAnnotation(Table.class).name();
	public static final String TABLE_EVOLUTION_CHAIN_NAME = EvolutionChain.class.getAnnotation(Table.class).name();
	public static final String TABLE_EVOLUTION_TRIGGER_NAME = EvolutionTrigger.class.getAnnotation(Table.class).name();
	public static final String TABLE_EXPERIENCE_NAME = Experience.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = Gender.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = Generation.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = GrowthRate.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = Item.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = ItemCategory.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = ItemFlag.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = ItemFlagMap.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = ItemFlavorSummary.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = ItemFlavorText.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = ItemFlingEffect.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = ItemGameIndices.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = ItemPocket.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = Location.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = LocationArea.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = LocationAreaEncounterRate.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = LocationGameIndices.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = Machine.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = Move.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = MoveBattleStyle.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = MoveChangelog.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = MoveDamageClass.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = MoveEffect.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = MoveEffectChangelog.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = MoveFlag.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = MoveFlagMap.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = MoveFlavorSummary.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = MoveFlavorText.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = MoveMeta.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = MoveMetaAilment.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = MoveMetaCategory.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = MoveMetaStatChange.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = MoveTarget.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = Nature.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = NatureBattleStylePreference.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = NaturePokeathlonStat.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = PalPark.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = PalParkArea.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = PokeathlonStat.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = Pokedex.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = PokedexVersionGroup.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = Pokemon.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = PokemonAbility.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = PokemonColor.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = PokemonDexNumber.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = PokemonEggGroup.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = PokemonEvolution.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = PokemonForm.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = PokemonFormGeneration.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = PokemonFormPokeathlonStat.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = PokemonGameIndices.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = PokemonHabitat.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = PokemonItem.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = PokemonMove.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = PokemonMoveMethod.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = PokemonShape.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = PokemonSpecies.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = PokemonSpeciesFlavorSummary.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = PokemonSpeciesFlavorText.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = PokemonStat.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = PokemonType.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = Region.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = Stat.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = SuperContestCombo.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = SuperContestEffect.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = Type.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = TypeEfficacy.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = TypeGameIndices.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = Version.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = VersionGroup.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = VersionGroupPokemonMoveMethod.class.getAnnotation(Table.class).name();
//	public static final String TABLE_REGION_NAME = VersionGroupRegion.class.getAnnotation(Table.class).name();
	public static final String TABLE_REGION_ENTITY_NAME = "Region";
}